name: build
on:
  workflow_dispatch:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build
        run: |
          git config --global --add safe.directory ${GITHUB_WORKSPACE}
          git config --global --add safe.directory ${GITHUB_WORKSPACE}/third_party/tensorflow
          git submodule update --init --recursive
          git submodule update --remote
          apt-get update
          apt-get install -y llvm-17 clang-17
          bazel build //tflite/java:tensorflowlitelib_stable
          find -name *.jar
          ls -l bazel-bin/tflite/java
      - name: publish
        run: |
          echo -n "${{ secrets.GPG_KEY}}" | base64 -d | gpg --import
          mkdir -p ~/.m2
          echo '<settings><servers><server><id>central</id><username>${{ secrets.MAVEN_USERNAME }}</username><password>${{ secrets.MAVEN_PASSWORD }}</password></server></servers></settings>' >~/.m2/settings.xml
          mvn -B deploy
        env:
          GPG_KEY: ${{ secrets.GPG_KEY }}
          #MAVEN_GPG_PASSPHRASE: ""
